# Generated by Django 5.0.1 on 2024-06-12 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.ImageField(default='users/default.png', upload_to='users/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TierListPost',
            fields=[
                ('id', models.IntegerField(default='7193922461037', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TierListEntry',
            fields=[
                ('id', models.IntegerField(default='21041462404107', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('total_points', models.IntegerField(default=0)),
                ('total_inputs', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tierlistpost')),
            ],
        ),
    ]
