# Generated by Django 5.1.15 on 2026-02-08 20:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TierListPost',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2026, 2, 8, 20, 21, 6, 174695, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=550)),
                ('is_private', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
                ('likes', models.ManyToManyField(related_name='likedtierlistposts', to='userprofile.profile')),
                ('tags', models.ManyToManyField(related_name='posttags', to='main.posttag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
