# Generated by Django 5.0.1 on 2024-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='41438368107109', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.IntegerField(default='3984263891063', primary_key=True, serialize=False),
        ),
    ]
