# Generated by Django 5.0.1 on 2024-06-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tierlistentry_id_alter_tierlistpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='9944708301084', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.IntegerField(default='651065710109645', primary_key=True, serialize=False),
        ),
    ]
