# Generated by Django 5.1.15 on 2026-02-08 21:23

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tier_posttag_created_at_posttag_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.BigIntegerField(default=main.models.create_post_id, primary_key=True, serialize=False),
        ),
    ]
