# Generated by Django 5.0.1 on 2024-06-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_id_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierlistentry',
            name='profile',
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='153765428913', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.IntegerField(default='75710210654365', primary_key=True, serialize=False),
        ),
    ]
