# Generated by Django 5.0.1 on 2024-06-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tierlistentry_profile_alter_tierlistentry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierlistpost',
            name='description',
            field=models.TextField(default='', max_length=550),
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='409336014225', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.IntegerField(default='412850317880', primary_key=True, serialize=False),
        ),
    ]
