# Generated by Django 5.0.1 on 2024-06-24 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tierlistpost_description_alter_tierlistentry_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tierlistpost',
            name='likes_link',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='8444105842624', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.IntegerField(default='106438309101050', primary_key=True, serialize=False),
        ),
    ]
