# Generated by Django 5.0.1 on 2024-06-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tierlistpost_likes_link_alter_tierlistentry_id_and_more'),
    ]

    operations = [
    ]
