# Generated by Django 5.0.1 on 2024-06-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240623_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='752362521842', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.IntegerField(default='5455573106217', primary_key=True, serialize=False),
        ),
    ]
