# Generated by Django 5.0.1 on 2024-06-24 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tierlistentry_id_alter_tierlistpost_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierlistpost',
            name='likes_link',
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='63361041015598', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.IntegerField(default='2630832832910', primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='tierlistpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='tierlistpost',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='tierlistpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
