# Generated by Django 5.0.1 on 2024-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_tierlistentry_id_alter_tierlistpost_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatedTierListEntry',
            new_name='EntryRating',
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='199068108823', primary_key=True, serialize=False),
        ),
    ]
