# Generated by Django 5.0.1 on 2024-07-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_ratedtierlistentry_entryrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='115070637192', primary_key=True, serialize=False),
        ),
    ]
