# Generated by Django 5.0.1 on 2024-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_tierlistentry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierlistentry',
            name='total_inputs',
        ),
        migrations.RemoveField(
            model_name='tierlistentry',
            name='total_points',
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='261010134106972', primary_key=True, serialize=False),
        ),
    ]
