# Generated by Django 5.0.1 on 2024-07-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_tierlistentry_total_inputs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierlistentry',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='1101510510102585', primary_key=True, serialize=False),
        ),
    ]
