# Generated by Django 5.0.1 on 2024-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_tierlistentry_average_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='30419710957108', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tierlistpost',
            name='tags',
            field=models.ManyToManyField(related_name='posttags', to='main.posttag'),
        ),
    ]
