# Generated by Django 5.0.1 on 2024-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_posttag_alter_tierlistentry_id_tierlistpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistentry',
            name='id',
            field=models.IntegerField(default='3108024185369', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tierlistpost',
            name='id',
            field=models.IntegerField(default='10290109628843', primary_key=True, serialize=False),
        ),
    ]
